direnvrc
This was clearing TMPDIR since it was first not setting the
`tmp_backup` local variable, and then, since `tmp_backup` was null, it
was unsetting TMPDIR.
=> Fix TMPDIR backup

README.md
It appears that the derivations produced by nix-direnv are removed when running nix's garbage collection. Troubleshooting this issue led me to [a git issue][1] in the NixOS/nix repo. Enabling both `keep-derivations` and `keep-outputs` worked for me as recommended, and now nix-direnv is working.
[1]: https://github.com/NixOS/nix/issues/2208
=> Update README.md with nix.conf changes needed for persistent derivations

direnvrc
Unsetting NIX_SSL_CERT_FILE and SSL_CERT_FILE stops `git pull` from working. Restore it from its previous value instead.
Resolves https://github.com/nix-community/nix-direnv/issues/6
=> Restore (NIX_)SSL_CERT_FILE to original value

direnvrc
Otherwise python does not find any certificates
=> direnvrc: do not set an empty NIX_SSL_CERT_FILE

README.md
Update readme with a more home-managery way of installing nix-direnv in home-manager.
=> readme: update home-manager instructions

README.md
Home-manager now supports the option [programs.direnv.enableNixDirenvIntegration](https://rycee.gitlab.io/home-manager/options.html#opt-programs.direnv.enableNixDirenvIntegration).
User does not need to set the `stdlib` option now.
=> Updated installation guide for home-manager

direnvrc
.version-suffix does not contain a newline and therefore fails with read
=> fix direnv strict_env evaluation

direnvrc
This avoids a `cannot create directory` error when a custom layout dir like `direnv_layout_dir=$HOME/.cache/nix-direnv/$pwdHash` is used and the cache dir doesn't exist.
This may happen when nix-direnv is used for the first time or when the cache has been cleared.
=> use mkdir -p for direnv_layout_dir

README.md
The static setup of `direnv_layout_dir` in `direnvrc` leads to the creation of separate layout dirs and nix shell caches for each subdirectory of a project.
Reason: When `direnvrc` is evaluated, `PWD` has the value of the calling user's shell, instead of pointing to the project directory (the dir containing `.envrc`).
Fix this by dynamically evaluating `$PWD` in a function.
Dynamic evaluation is also required when `.envrc` includes (via `source_*`) `.envrc` files from other projects because `$PWD` changes in this case.
Cache the computed layout paths because `shasum` is fairly expensive (13 ms on my desktop system).
=> README: fix direnv_layout_dir setup

direnvrc
fixes #54
readpath is not available on macOS.
=> use readlink instead of realpath

direnvrc
Without this patch, the following error occurs when using a git checkout of nixpkgs:
```
/run/current-system/sw/share/nix-direnv/direnvrc:115: .git/refs/heads/nixos-unstable: No such file or directory
```
=> direnvrc: Fix reading of nixpkgs version from git checkout

README.md
When I followed the README, direnv did not get hooked into zsh because I had zsh installed at the system level, rather than enabled in my `home-manager` configuration. I suggest you make it explicit that it must be the case for the `home.nix` changes to work.
=> Avoid pitfall in home-manager config instructions

README.md
Enable a little more syntax highlighting in the `README.md` by adding "Nix" to three code blocks missing it, and "bash" to one.
One in-between is intentionally left un-typed due to being a text-based config format rather than a common script or language.
=> Add Missing Code Type Tags

README.md, direnvrc
This allows using flake.nix out of tree, which is very appreciable
if you develop in a big repository as flake evaluation will copy the
whole git archive to store everytime it changes.
To give a more concrete example, I have my dev environments in /etc/nixos which is stable and relatively small, so I use it with package name argument for ech project e.g. `use flake /etc/nixos#linux` in .envrc with:
http://cgit.notk.org/asmadeus/nixos-config.git/tree/pkgs/linux/default.nix
loaded from http://cgit.notk.org/asmadeus/nixos-config.git/tree/pkgs/default.nix with callPackage
loaded from http://cgit.notk.org/asmadeus/nixos-config.git/tree/flake.nix as output's packages.x86_64-linux
Using an in-repo flake.nix for linux kernel development/testing didn't really work well; I considered an …
=> use flake: allow optional flake expression

direnvrc, tests/test.py, tests/testenv/shell.nix
This makes the behavior of `use flake` consistent with that of `use
nix`.
Resolve #90.
=> flakes: Don't run shellHook on cached dev shells

tests/test.py
The majority of the test code is just creating the stdout data against
which to make assertions. Increasing the test cases will be more
manageable if the assertions are separate from this data generation.
It is also a generally preferred style to have one assertion per test,
because this way all assertions run even if others fail and each test
only fails for one reason. It also facilitates better test documentation
and adding additional tests without increasing complexity.
=>  test.py: isolate assertions; DRY data generation 

README.md
Configuration name changed in: https://github.com/nix-community/home-manager/commit/e0f2949c981a636ff1a75bd075e2a614af3bafb1
=> Update installation via home-manager documentation

default.nix
Fixes:
```
nix-direnv on  master [?] 
❯ nix build .#
trace: Warning: `stdenv.lib` is deprecated and will be removed in the next release. Please use `lib` instead. For more information see https://github.com/NixOS/nixpkgs/issues/108938
nix-direnv on  master [?] 
❯ nix --version
nix (Nix) 2.4pre20210601_5985b8b
```
=> fix(warn): stdenv.lib missing

README.md
Due to NixOS making nix-direnv use the stable version of nix by
default we get this error when using flakes:
direnv: using flake
error: 'print-dev-env' is not a recognised command
[…]
error: 'flake' is not a recognised command
This can be worked around by passing `enableFlakes = true` to the
package.
See also #92.
=> fix(doc): document how to enable flake support on NixOS

flake.nix
Provide an overlay (and consume it) so that flake users could add a nix module like:
```nix
{
nixosModules = {
add-overlays = {
nixpkgs.overlays = [ nix-direnv.overlay ];
environment.systemPackages = with pkgs; [
direnv
nix-direnv
];
};
};
}
```
=> chore: add overlay

direnvrc
On macOS, `$TMPDIR` is usually a private temp dir separate from
`/tmp` - this trips up some programs like `emacsclient` when under
nix-shell.
cf https://github.com/NixOS/nixpkgs/issues/55201
=> direnvrc: don't override TMPDIR

direnvrc
This change permits to make multiple calls to use_nix, with different
arguments passed to it. It will generate a cache file for each distinct
"argument list" rather than based solely on the nixpkgs version.
=> Add a suffix to cache file to allow multiple calls to use_nix

direnvrc
macOS has `-i` but it insists on writing backup files.
fixes https://github.com/nix-community/nix-direnv/issues/120
=> useFlake(): fix sed invocation on legacy operating systems

flake.nix, shell.nix
This will make it so that running `nix develop` in this repo is equivalent to `nix-shell`
I'm not sure if this is what we want as it means `nix develop` will no longer have take the phases from `default.nix`
=> flake.nix: Import `shell.nix` as `devShell`

README.md
Remove `nix-direnv.enableFlake` option from the doc as Flake support is now always enabled.
Fixes #131
=> remove enableFlake from the doc for home-manager

README.md, direnvrc
Closes #135.
The fix here is simple. The arguments passed to `use_flake` are already an array.
Assuming that the first entry in that array is a flake specifier is still fine,
but this change allows us to fill the rest of the array with  other arguments to pass to `print-dev-env`.
I don't anticipate this being completely finalized, as tests should be built for this functionality (though I am unsure how right now) and the documentation should be updated to reflect the change. 
This is open for discussion as I am unsure if this is a change that the maintainers generally want.
=> Allow passing arguments to print-dev-env invocation

direnvrc
2.21.3 introduces extglob to direnv's stdlib.
This means we need at least 2.21.3 to execute nix_direnv_version.
This just enforces a previously unstated dependency.
The other possible solution is to directly call `shopt -s extglob` in `nix_direnv_version`,
but I'm afraid of that having effects in other places OR of nix-direnv depending on other post-direnv-2.21.3-isms.
Part of #139
=> Declare (and enforce) a minimum direnv version

README.md, direnvrc, template/.envrc
* Update hashes
* Hash obtained via:
```sh
direnv fetchurl 'https://raw.githubusercontent.com/nix-community/nix-direnv/master/direnvrc' \
| grep -m1 -o 'sha256-.*'
```
* Bump tag to 1.6.1 in:
* `README.md`
* `direnvrc`
* `template/.envrc`
This release includes the following changes:
* Allow watching of arbitrary files for nix flake updates ([#148][1])
[1]: https://github.com/nix-community/nix-direnv/pull/148
=> Release version 1.6.1

direnvrc
Closes #159
Just make sure that the major version is the same when checking the minor and that major and minor are the same when checking patch.
=> Fix nix_direnv_version to properly handle major version bumps

direnvrc
Neither `in_packages` nor `nixfile` should require prefixing with a `-`.
=> Fix path and package handling in use_nix arg parsing

direnvrc
Extra arguments passed to `use nix` (such as `--arg` or `--argstr`)
were getting clobbered by an errant re-definition. Removed that
definition so those arguments get passed along.
Due to #190
=> Ensure extra arguments passed to shell

direnvrc
With direnv’s `strict_env`, previously got an error
> NIX_BUILD_TOP: unbound variable
I tried to adjust the tests to catch this, but unfortunately I could not
get them to fail as-is.
Maybe fixes #128, though that also makes me question if this is the best solution to the problem, or just a workaround.
=> Fix error with strict_env

templates/flake/flake.nix
Running `nix flake check` on a flake created using this template results in the following warning:
> warning: flake output attribute 'devShell' is deprecated; use 'devShells.\<system\>.default' instead
This PR updates the flake template accordingly.
=> Replace deprecated devShell attribute key

direnvrc, tests/test_gc.py, tests/testenv/shell.nix
As discussed in #235, nix-direnv currently does not remove the profiles and GC roots created for older version of the environment. This PR aims to fix this.
It adds a function `_nix_clean_old_gcroots` that is called before updating the environment and removes all the `nix-{flake,profile}*` from the local `.direnv` directory as well as the corresponding GC roots. Since this function reuses the code of `_nix_add_gcroots` for escaping path, this code is now run by calling the `_nix_strip_escape_path` function.
I only tested this PR with the current test-suite as I didn't take the time to understand what the tests were doing. Let me know if you want me to add some tests.
=> remove old gcroots when the environment is updated

README.md
GitHub renders 
```md
<details>
<summary>...</summary>
```
as
```html
<details><summary>...</summary>
```
but renders
```md
<details>
<summary>...</summary>
```
as
```html
<details><summary>...</summary>
<h3>...</h3>
```
which is more likely to be what the authors of the README.md intended.
=> fix: render `###`s as `<h3>`s in README

direnvrc
after importing from the nix environment
we currently concatenate the new and old values of XDG_DATA_DIRS,
which means if the nix environment reused or recreated the old values
they are now present twice.
XDG_DATA_DIRS is specified to be a "set",
and some software (GNOME for example) assume that its entries are unique.
this change reconstructs XDG_DATA_DIRS
by looping over the new and old entries
and adding the new ones among them.
it normalizes the entries by removing trailing slashes
to make duplicate detection a bit easier.
it could instead loop over only the old entries and append them to the new ones,
that would save one line of code but make duplicate detection a bit more involved.
looping only over the new entries would make invert their order.
=> ensure XDG_DATA_DIRS contains unique entries

direnvrc, tests/direnv_project.py, tests/test_use_nix.py
Should resolve #270.
I want to make sure the tests pass before we merge, but the fix is pretty trivial
=> Don't track $nixfile if it is empty

README.md, bors.toml, templates/flake/flake.nix
Since https://github.com/NixOS/nixpkgs/commit/c6b62f2381571cc83c6c32ef4984fabcbb4ca892 we now have the `packages` attribute which at least in the nixpkgs repository seems to be preferred over `nativeBuildInputs` in the `mkShell` context. 
I also removed the empty `buildInputs` attribute. These two changes makes the template a bit more beginner-friendly in my opinion and aligns it with the documentation on `pkgs.mkShell`: https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-mkShell
=> Prefer `packages` over `nativeBuildInputs`

README.md
The version has been updated (from 2.2.0 to 2.2.1) but the hash has not been updated, resulting in the following error
direnv: error hash mismatch. Expected 'sha256-5EwyKnkJNQeXrRkYbwwRBcXbibosCJqyIUuz9Xq+LRc=' but got 'sha256-zelF0vLbEl5uaqrfIzbgNzJWGmLzCmYAkInj/LNxvKs='
=> source_url install: fix hash

direnvrc
=> fix error message if flake-inputs directory already exists

direnvrc
`read` fails if it encounters EOF before the delim, the `.version` file does not always have a newline, so `read` fails in that case. If the env has `set -e` then this will abort. So add a newline to the end always. Doesn’t seem to matter if there is more than one.
=> Fix reading nixpkgs version without trailing newline

direnvrc
This PR resolves issue #305 by querying the nix version through ``nix --version`` and testing that.
It also adds error reporting of the current nix version in case the test fails.
=> Check nix version directly

direnvrc
Do so by no longer hard-coding gcroot paths, and defer to Nix to manage things.
https://github.com/NixOS/nix/pull/5226
=> Use nix-store --add-root instead of hard-coding gcroot path (fix for Nix 2.14+)

direnvrc
strict_env basically does `set -e`, and this fails in that case. We handle it failing in the `if` on the subsequent line.
I’m curious if `setup_envrc` in the tests should be changed to set `strict_env` to catch this sort of thing—or maybe parameterize all the tests over both cases?
=> Fix use nix with no nixpkgs when strict_env

tests/test_gc.py
In 988193f812003cdf34e5f550487c40ed7163fb08 a new input was added to the flake, and thus broke this test.
=> Fix failing tests

README.md, direnvrc
Adding nix_direnv_manual_reload to .envrc will avoid the automatic update of the nix environment on changes and allow the user to issue a command to update the nix environment explicitly.
Sometimes it takes a long time to rebuild the nix environment and it happens in times. Switching branches in or rebasing can be painful since nix will re-evaluate between nix file changes.
This blog post explains the problems with blocking the shell: https://dev.to/allenap/some-direnv-best-practices-actually-just-one-4864
Example usage:
```
$ cat .envrc
source nix-direnv/direnvrc
nix_direnv_manual_reload
use_flake
$ touch flake.nix
direnv: loading ~/tst/.envrc
direnv: nix-direnv: cache is out of date. use "nix-direnv-reload" to reload.
direnv: export +AR +AS <... snip ...>
$ nix-direnv-reload
direnv: …
```
=> Allow manual reload of nix environment.

README.md
The home-manager options have been changed (namely, nix-direnv is an option inside of programs.direnv). Also included the option for enabling Bash integration and left a note for how to enable integration for other shells through HM options... I also removed the section on keep-outputs and keep-derivations since, based on the Nix Manual, outputs/derivations that are registered as GC roots will be kept regardless of these settings (and as I understand it, nix-direnv does indeed register shells as GC roots). So telling users to enable these options would just keep behind extra garbage for them (in my opinion, one of the reasons to use nix-direnv is so that you DON'T have to enable these options and can keep garbage collecting everything else per usual.
=> Update home-manager section of README

direnvrc
This bit me recently. Usually `use flake -L` and `use flake -L some-flake` work without errors. When an error does occur, the resulting error messages can be obscure.
=> Warn when `use flake` receives a flag for the first argument

README.md
The nixpkgs direnv module automatically sources nix-direnv so no need to add it to the users direnvrc
and the persistDerivations option was removed as it's no longer needed
:)
=> update README... again

direnvrc
Closes #400.
Cannot request @gmacon for review, but would appreciate his feedback.
=> Fix Manual Reload script with non-standard layout dir

README.md
shell.nix file is used first if it exists, see https://github.com/nix-community/nix-direnv/blob/9178f71653285fff85b6a8712821b95273f95582/direnvrc#L340-L344
=> Fix Nix file order docs

direnvrc
In many cases they will shell.nix will depend on default.nix and when a user switches from default.nix to shell.nix we also want to invalidate the cache.
fixes https://github.com/nix-community/nix-direnv/issues/409
=> use_nix: watch for both shell.nix and default.nix

README.md, default.nix, direnvrc
`nix_direnv_watch_file` is replaced with a function that wraps `watch_file` and issues a deprecation warning.
See #408 (which this fixes) for discussion.
=> use direnv-builtin `DIRENV_WATCHES` to list watched files

direnvrc
Small problem with a20b32d. In my environment (direnv 2.32.2) the keys in `DIRENV_WATCHES` are capitalized.
=> _nix_direnv_watches: update path regex to match capitalized path

flake.nix
Not needed since this repo switched to buildbot in https://github.com/nix-community/nix-direnv/pull/424.
=> flake: remove garnix nixConfig

templates/flake/flake.nix
fixes https://github.com/nix-community/nix-direnv/issues/431
It's probably for the best if it's also deadnix-safe for other users
=> fix template after treefmt

.envrc
I believe this way catches all dependencies of the shell environment.
=> envrc: watch direnvrc and *.nix

default.nix, direnvrc, scripts/create-release.sh
This prepends `coreutils` and `direnv` to `$PATH` in addition to `nix` in order to make this self-contained.
Fixes #440.
=> make self-contained

direnvrc
fixes https://github.com/nix-community/nix-direnv/issues/446
=> don't rely on direnv to be in $PATH

default.nix, direnvrc
This extends #447 by using `$direnv` to call direnv.
I've also modified the version check skip for nix to be less fragile.
=> Fixup `$direnv` usage

direnvrc
This function is used in our README for a long time to upgrade nix-direnv. Now it's failing execution instead.
=> fix nix_direnv_version terminating direnv

direnvrc
This change fixes regression introduced in commit
4bf5d40290981c867d70f6d3c0d505dd03bc2c0d. In particular, we should not be passing flake URI without schema to the nix flake archive command.
@mergify queue
=> Fix local flakes when prefixed with "path:" (again)

README.md, direnvrc, flake.nix, tests/test_gc.py, tests/test_use_nix.py
=> Issue a warning if we are falling back to the old shell environment

direnvrc
These errors only happen with `strict_env` or equivalent (`set -u`), and in the following cases:
- When using `use flake` incorrectly, for example passing a flag as first and only argument: `use flake --impure`
- When using `use nix` with flags that require extra arguments, without the arguments: `use nix -A`, `use nix -o optionName`, `use nix -o`...
=> Fix unbound shell variable errors on strict mode

README.md, default.nix, direnvrc
First, we try to use the ambient Nix version.
Then, we try to use $NIX_DIRENV_FALLBACK_NIX, which is set by default, but can also be overridden by the user.
Only then, if neither is available, we fail.
Fixes #451.
=> Use ambient Nix when available, with a two stage fallback

direnvrc
It's only initialized to `0` if it's not already set.
This fixes a niche-ish direnv use-case: I have `nix_direnv_manual_reload` set globally (inside my `direnvrc` config file). It works, but if I have nested envfiles it will be disabled (unless specified again). This can also be triggered by having `nix_direnv_manual_reload` on the nested `.envrc` but not on the outer one.
```bash
cd "$(mktemp -d)"
echo $'
{
inputs.nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
outputs =
{ nixpkgs, ... }:
let
forEachSystem =
f: nixpkgs.lib.genAttrs nixpkgs.lib.systems.flakeExposed (system: f nixpkgs.legacyPackages.system);
in
{
devShells = forEachSystem (pkgs: {
default = pkgs.mkShell { };
});
};
}' >flake.nix
echo 'use flake' >.envrc
mkdir inner
echo $'
nix_direnv_manual_reload
source_up
' …
```
=> Respect existing _nix_direnv_manual_reload

templates/flake/flake.nix
flake-utils provides finer control over "default systems" using [nix-systems](https://github.com/nix-systems).  It seemed reasonable to expose its `systems` input also in nix-direnv template.
<details><summary>Click here for the log</summary>
```sh
❯ nix fmt
warning: Git tree '/Users/ic/dev/nix-direnv' is dirty
WARN format: no formatter for path: LICENSE
WARN format: no formatter for path: pyproject.toml
traversed 33 files
emitted 33 files for processing
formatted 28 files (1 changed) in 680ms
nix-direnv on  master
❯ nix flake check --all-systems
nix-direnv on  master took 29s
❯
```
</details>
=> Added `nix-systems` input

templates/flake/flake.nix
Removed unsupported .com in nix-systems url input.
=> Fix syntax for nix-systems input

direnvrc
I am not sure why, but on docker bind mounts using virtiofs and gcsFuse, `-x` is always true for a file which exists.  This means that, before this commit was merged, when using nix-direnv in manual mode on a devcontainer with docker desktop on mac, `nix-direnv-reload` would be created and then not set as executable, and if they tried to run it users would see an error like `bad interpreter: Permission denied`.  After this commit is merged, these scenarios work.
Here's some discussion: https://github.com/docker/for-mac/issues/5029 
Other tools have run into this: https://github.com/pre-commit/identify/pull/189
=> Always set nix-direnv-reload as executable

direnvrc
It's to be expected in a git repository that our environment will contain non-committed code. No need to warn about that.
=> don't warn about dirty trees

direnvrc
Instead of the current behavior of always trying to call the expression as a function, or alternatively, trying to implement autocalling manually with `builtins.isFunction`.
Fixes #285.
=> rely on function autocalling

direnvrc
Since a few days ago (so I assume starting at [direnv 2.36.0](https://github.com/direnv/direnv/releases/tag/v2.36.0)), the `DIRENV_LOG_FORMAT` environment variable is not set by default. This breaks `nix-direnv` every time it's called with `strict_env` due to an unbound variable error.
Even if the variable was accessed safely, warnings won't be rendered anymore because it's empty and we skip printing anything when that happens.
With this approach, we use the stdlib `log_status`, and just wrap it around ANSI escapes for the yellow color.
This has the advantage of delegating the logging format logic back to `direnv`, but it might be possible that at some point in the future `direnv` sanitizes the strings and breaks this solution. However, the alternative is to keep relying on …
=> Fix warnings not being printed

README.md
The dollar signs are unnecessary in this situation, and should not be included. It is easier to copy/paste and less noisy if the dollar signs are omitted when they are not needed.
Detailed explanation:
<https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md014.md>
=> Fix dollar sign usage before commands without showing output in README

README.md
Previous version of these instructions did not make it very clear that you need to have nix-direnv _together_ with regular direnv.
As a newcomer, I had to learn this the hard way and spend some time debugging this. I'm sure this will be very helpful to other people like me.
Even better, why not even specify direnv as a `buildInput` for `nix-direnv` in `flake.nix`?
=> Add details for `nix profile` installation method

direnvrc
This fixes version detection if nixpkgs is a symbolic link into the nix store:
```
$ head -3 shell.nix
{
pkgs ? import <nixpkgs> { },
}:
$ nix eval --impure --expr '<nixpkgs>'
/etc/nix/path/nixpkgs
$ nix eval --impure --expr '<nixpkgs>' | xargs realpath
/nix/store/mcvd7n2ii0nbhpcl56mbb7nhy3005zhv-source
$ ll .direnv # before
total 76K
drwxr-xr-x 1 r r  34 2023.10.13 17:02 bin/
lrwxrwxrwx 1 r r  57 2025.06.14 20:57 nix-profile-unknown -> /nix/store/32xvp8j127n0n4px6hiwpz98zpaz1gx3-nix-shell-env
-rw-r--r-- 1 r r 71K 2025.06.14 20:57 nix-profile-unknown.rc
$ ll .direnv # after
total 76K
drwxr-xr-x 1 r r  34 2023.10.13 17:02 bin/
lrwxrwxrwx 1 r r  57 2025.06.14 20:59 nix-profile-25.11-mcvd7n2ii0nbhpcl -> /nix/store/32xvp8j127n0n4px6hiwpz98zpaz1gx3-nix-shell-env
-rw-r--r-- 1 r r 71K 2025.06.14 …
```
=> resolve symbolic links to nixpkgs
