nix-community/nix-direnv

README.md

cc @zimbatm @tviti 
related to https://github.com/nix-community/nix-direnv/issues/3

Document compatibility problems

---

.github/workflows/test.yml
direnvrc
tests/test.py

a95abd152a396137d82898ee589b8cb734a6a6f0 broke this

fix persistent derivation link

---

direnvrc

fix incorrectly spelled variable

---

direnvrc

this variable might be useful in direnv to expose different behavior
depending on calling shell.
fixes https://github.com/nix-community/nix-direnv/issues/45

don't override SHELL

---

README.md

Sorry, I've just noticed these after re-reading my last PR.

README: minor formatting/wording fixes

---

.github/workflows/test.yml
direnvrc
tests/test.py
tests/testenv/flake.nix

Before it just add a gc root with to a symlink to the current directory.

properly register flake source gc root

---

direnvrc

Other solution to https://github.com/nix-community/nix-direnv/pull/69

Preserve XDG_DATA_DIRS

---

direnvrc

Should fix #74 but i haven't started to use flakes myself yet, so if someone with a bit more familiar could try it out...

Dont merge: save XDG_DATA_DIRS in flakes

---

direnvrc

see: https://discourse.nixos.org/t/content-addressed-nix-call-for-testers/12881/36?u=bbigras

don't override experimental-features

---

direnvrc

This reverts commit 5996ecbfdbb203c3d9b4fc909374622bdaf23181.

Revert "async nix-shell"

---

README.md

Closes https://github.com/nix-community/nix-direnv/issues/115

Explain customizing the nix file name

---

.github/workflows/test.yml
tests/test.py

fixes https://github.com/nix-community/nix-direnv/pull/123

Upgrade ci

---

README.md
direnvrc

These changes should resolve #197 and hopefully resolve #189.
Pinging @jneem, @alexshpilkin, @PaulGrandperrin as well to ensure this resolves the issues in question.

Add nixfile to watches and add --no-write-lock-file

---

default.nix

this has been changed to an error on nixpkgs-unstable. unsure how it impacts folks who aren't using unstable - I expect last release should work?

fix nix flakes reference to nixFlakes

---

README.md

direnv itself suggests this path instead of ~/.direnvrc: https://direnv.net/man/direnv.1.html#files

Suggest XDG_CONFIG_DIR rc file for direnv

---

README.md

fixes https://github.com/nix-community/nix-direnv/issues/378

drop keep-outputs/keep-derivations from README

---

direnvrc

fixes https://github.com/nix-community/nix-direnv/issues/393

fix _nix_direnv_force_reload not beeing bound

---

direnvrc

do not deprecate nix_direnv_watch_file yet (2.5.1)

---

.mergify.yml
README.md
default.nix
flake.lock
flake.nix
lint.nix
shell.nix
templates/flake/flake.nix
tests/direnv_project.py
tests/testenv/flake.nix
tests/testenv/shell.nix
treefmt.nix

Gives us `nix fmt` integration and a ci check without much code.

replace lint with treefmt

---

README.md
default.nix
direnvrc
flake.nix
test-runner.nix

a  small cleanup

---

direnvrc

Restore terminfo from calling shell

---

README.md

nix-env has too many usability issues.

README: drop nix-env installation

---

README.md

Home manager changed its location, this adjusts the README accordingly.

Update path for home.nix

---

direnvrc

Closes #491, pending user approval.

GH-491: Explictly set IN_NIX_SHELL to more closely mimic nix-shell execution

---

.github/workflows/auto-merge.yaml
.github/workflows/update-flake-lock.yml

also use app token for update-flake-lock so that auto-merge actions can be triggered

add auto-merge github action

---

README.md
templates/flake/.envrc

Update checksums for release 3.0.7 of nix-direnv

Update checksums for release 3.0.7 of nix-direnv

---

README.md
templates/flake/.envrc

Update checksums for release 3.1.0 of nix-direnv

Update checksums for release 3.1.0 of nix-direnv
